trigger:
- master

variables:
  sdkVersion: '5.0.201'
  project: 'FeedReader/FeedReader.csproj'
  configuration: 'Release'

jobs:
- job: 'Build'
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
        rid: 'linux-x64'
        suffix: 'Linux64'
      mac:
        imageName: 'macos-latest'
        rid: 'osx-x64'
        suffix: 'OSX64'
      windows:
        imageName: 'windows-latest'
        rid: 'win-x64'
        suffix: 'Win64'
  pool:
    vmImage: $(imageName)

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK 5.0'
    inputs:
      packageType: sdk
      version: '$(sdkVersion)'

  - script: dotnet publish $(project) -r $(rid) -c Release -o build -v n -p:PublishTrimmed=true -p:PublishSingleFile=true
    displayName: 'Publish project'

  - task: ArchiveFiles@2
    condition: ne(variables.rid, 'linux-x64')
    displayName: 'Archive'
    inputs:
      rootFolderOrFile: 'build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/FeedReader.$(suffix).zip'

  - task: ArchiveFiles@2
    condition: eq(variables.rid, 'linux-x64')
    displayName: 'Archive'
    inputs:
      rootFolderOrFile: 'build'
      includeRootFolder: false
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/FeedReader.$(suffix).tar.gz'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      artifactName: 'publish'
